use crate::ast::*;
use crate::check::CheckedProgram;
use crate::units;
use std::collections::{BTreeMap, HashMap};

pub fn emit_c(checked: &CheckedProgram) -> Result<String, String> {
    let mut out = String::from(
        "/* generated by vibec; do not edit */\n#include <stdint.h>\n#include <stdbool.h>\n#include <stddef.h>\n#include <stdio.h>\n\ntypedef struct { float *data; size_t len; } vibe_array_f32;\ntypedef struct { double *data; size_t len; } vibe_array_f64;\ntypedef struct { int32_t *data; size_t len; } vibe_array_i32;\ntypedef struct { int64_t *data; size_t len; } vibe_array_i64;\n\n",
    );
    let function_results: HashMap<String, TypeSyntax> = checked
        .program
        .functions
        .iter()
        .map(|function| (function.id.clone(), function.result.clone()))
        .collect();
    out.push_str("#include <complex.h>\ntypedef struct { float _Complex *data; size_t len; } vibe_array_complex64;\n");
    out.push_str("typedef struct { double _Complex *data; size_t len; } vibe_array_complex128;\n");
    for f in &checked.program.functions {
        out.push_str(&signature(f));
        out.push_str(";\n");
    }
    out.push('\n');
    for f in &checked.program.functions {
        out.push_str(&signature(f));
        out.push_str(" {\n");
        let mut env: HashMap<String, TypeSyntax> = f
            .params
            .iter()
            .map(|p| (p.name.clone(), p.ty.clone()))
            .collect();
        emit_block(&f.body, &mut env, &function_results, 1, &mut out)?;
        out.push_str("}\n\n");
    }
    if checked
        .program
        .functions
        .iter()
        .any(|f| f.id == "@app.main")
    {
        out.push_str(&format!(
            "int main(void) {{ return (int){}(); }}\n",
            mangle("@app.main")
        ));
    }
    Ok(out)
}

fn signature(f: &Function) -> String {
    let params = if f.params.is_empty() {
        "void".into()
    } else {
        f.params
            .iter()
            .map(|p| format!("{} {}", c_type(&p.ty), local_name(&p.name)))
            .collect::<Vec<_>>()
            .join(", ")
    };
    format!("{} {}({})", c_type(&f.result), mangle(&f.id), params)
}

fn emit_block(
    body: &[Stmt],
    env: &mut HashMap<String, TypeSyntax>,
    function_results: &HashMap<String, TypeSyntax>,
    depth: usize,
    out: &mut String,
) -> Result<(), String> {
    let pad = "    ".repeat(depth);
    for stmt in body {
        match stmt {
            Stmt::Let {
                name,
                mutable: _,
                annotation,
                value: Expr::Array(values),
            } => {
                if values.is_empty() {
                    return Err("empty array code generation is unsupported".into());
                }
                let element = match annotation {
                    Some(TypeSyntax::Array { element, .. }) => element.clone(),
                    _ => match &values[0] {
                        Expr::Complex { .. } => Scalar::Complex64,
                        Expr::Number { scalar, .. } => scalar.clone(),
                        _ => return Err("array literal element type must be explicit".into()),
                    },
                };
                out.push_str(&format!(
                    "{pad}{} {}_storage[] = {{",
                    scalar_c(&element),
                    local_name(name)
                ));
                for (i, v) in values.iter().enumerate() {
                    if i > 0 {
                        out.push_str(", ");
                    }
                    out.push_str(&emit_expr(v)?);
                }
                out.push_str("};\n");
                out.push_str(&format!(
                    "{pad}vibe_array_{} {} = {{ {}_storage, {} }};\n",
                    element.name(),
                    local_name(name),
                    local_name(name),
                    values.len()
                ));
                let unit = match annotation {
                    Some(TypeSyntax::Array { unit, .. }) => unit.clone(),
                    _ => match &values[0] {
                        Expr::Number { unit, .. } => unit.clone(),
                        _ => None,
                    },
                };
                env.insert(
                    name.clone(),
                    TypeSyntax::Array {
                        element,
                        rank: 1,
                        unit,
                        mutable: true,
                    },
                );
            }
            Stmt::Let {
                name,
                annotation,
                value,
                ..
            } => {
                let ty = annotation
                    .clone()
                    .unwrap_or_else(|| infer_syntax(value, env, function_results));
                out.push_str(&format!(
                    "{pad}{} {} = {};\n",
                    c_type(&ty),
                    local_name(name),
                    emit_expr(value)?
                ));
                env.insert(name.clone(), ty);
            }
            Stmt::Assign { target, value } => out.push_str(&format!(
                "{pad}{} = {};\n",
                emit_expr(target)?,
                emit_expr(value)?
            )),
            Stmt::For {
                index,
                start,
                end,
                body,
            } => {
                out.push_str(&format!(
                    "{pad}for (int64_t {} = {}; {} < {}; ++{}) {{\n",
                    local_name(index),
                    emit_expr(start)?,
                    local_name(index),
                    emit_expr(end)?,
                    local_name(index)
                ));
                let mut loop_env = env.clone();
                loop_env.insert(index.clone(), TypeSyntax::Scalar(Scalar::I64, None));
                emit_block(body, &mut loop_env, function_results, depth + 1, out)?;
                out.push_str(&format!("{pad}}}\n"));
            }
            Stmt::Return(Some(v)) => out.push_str(&format!("{pad}return {};\n", emit_expr(v)?)),
            Stmt::Return(None) => out.push_str(&format!("{pad}return;\n")),
            Stmt::Print {
                value: Expr::String(value),
                ..
            } => {
                out.push_str(&format!("{pad}puts(\"{}\");\n", c_string(value)));
            }
            Stmt::Print { value, unit } => {
                let divisor = unit
                    .as_deref()
                    .map(|u| units::parse(Some(u)).map(|x| x.scale))
                    .transpose()?
                    .unwrap_or(1.0);
                let format = unit
                    .as_deref()
                    .map(|unit| format!("%.12g {unit}\\n"))
                    .unwrap_or_else(|| "%.12g\\n".into());
                out.push_str(&format!(
                    "{pad}printf(\"{format}\", (double)({}) / {:.17e});\n",
                    emit_expr(value)?,
                    divisor
                ));
            }
            Stmt::Expr(v) => out.push_str(&format!("{pad}(void)({});\n", emit_expr(v)?)),
        }
    }
    Ok(())
}

fn emit_expr(expr: &Expr) -> Result<String, String> {
    Ok(match expr {
        Expr::Complex { real, imag } => format!(
            "__builtin_complex({}, {})",
            emit_number(real, &Scalar::F32, 1.0)?,
            emit_number(imag, &Scalar::F32, 1.0)?
        ),
        Expr::String(_) => return Err("string values are only valid directly inside print".into()),
        Expr::Number { text, scalar, unit } => {
            let scale = units::parse(unit.as_deref())?.scale;
            emit_number(text, scalar, scale)?
        }
        Expr::Var(name) => local_name(name),
        Expr::Array(_) => return Err("array literal is only valid in a let binding".into()),
        Expr::Index { array, index } => {
            format!("({}).data[{}]", emit_expr(array)?, emit_expr(index)?)
        }
        Expr::Call { function, args } if function == "len" => {
            format!("(int64_t)({}).len", emit_expr(&args[0])?)
        }
        Expr::Call { function, args } => format!(
            "{}({})",
            mangle(function),
            args.iter()
                .map(emit_expr)
                .collect::<Result<Vec<_>, _>>()?
                .join(", ")
        ),
        Expr::Binary { op, left, right } => {
            format!("({} {op} {})", emit_expr(left)?, emit_expr(right)?)
        }
        Expr::Unary { op, value } => format!("({op}{})", emit_expr(value)?),
    })
}

fn infer_syntax(
    expr: &Expr,
    env: &HashMap<String, TypeSyntax>,
    function_results: &HashMap<String, TypeSyntax>,
) -> TypeSyntax {
    match expr {
        Expr::Complex { .. } => TypeSyntax::Scalar(Scalar::Complex64, None),
        Expr::String(_) => TypeSyntax::None,
        Expr::Number { scalar, unit, .. } => TypeSyntax::Scalar(scalar.clone(), unit.clone()),
        Expr::Var(v) => env.get(v).cloned().unwrap_or(TypeSyntax::None),
        Expr::Array(v) => match v.first() {
            Some(Expr::Number { scalar, unit, .. }) => TypeSyntax::Array {
                element: scalar.clone(),
                rank: 1,
                unit: unit.clone(),
                mutable: true,
            },
            _ => TypeSyntax::None,
        },
        Expr::Index { array, .. } => match infer_syntax(array, env, function_results) {
            TypeSyntax::Array { element, unit, .. } => TypeSyntax::Scalar(element, unit),
            _ => TypeSyntax::None,
        },
        Expr::Binary { left, .. } | Expr::Unary { value: left, .. } => {
            infer_syntax(left, env, function_results)
        }
        Expr::Call { function, .. } if function == "len" => TypeSyntax::Scalar(Scalar::I64, None),
        Expr::Call { function, .. } => function_results
            .get(function)
            .cloned()
            .unwrap_or(TypeSyntax::None),
    }
}

fn c_type(ty: &TypeSyntax) -> String {
    match ty {
        TypeSyntax::Scalar(s, _) => scalar_c(s).into(),
        TypeSyntax::Array { element, .. } => format!("vibe_array_{}", element.name()),
        TypeSyntax::None => "void".into(),
    }
}
fn scalar_c(s: &Scalar) -> &'static str {
    match s {
        Scalar::Complex64 => "float _Complex",
        Scalar::Complex128 => "double _Complex",
        Scalar::Bool => "bool",
        Scalar::I32 => "int32_t",
        Scalar::I64 => "int64_t",
        Scalar::F32 => "float",
        Scalar::F64 => "double",
    }
}
pub fn mangle(id: &str) -> String {
    let mut output = String::from("vibe");
    for byte in id.as_bytes() {
        output.push_str(&format!("_{byte:02x}"));
    }
    output
}

fn local_name(name: &str) -> String {
    let mut output = String::from("v");
    for byte in name.as_bytes() {
        output.push_str(&format!("_{byte:02x}"));
    }
    output
}

fn emit_number(text: &str, scalar: &Scalar, scale: f64) -> Result<String, String> {
    match scalar {
        Scalar::F32 => {
            let value = text.parse::<f32>().map_err(|error| error.to_string())? * scale as f32;
            if !value.is_finite() {
                return Err("unit scaling overflows an f32 literal".into());
            }
            Ok(format!("({value:.9e}f)"))
        }
        Scalar::F64 => {
            let value = text.parse::<f64>().map_err(|error| error.to_string())? * scale;
            if !value.is_finite() {
                return Err("unit scaling overflows an f64 literal".into());
            }
            Ok(format!("({value:.17e})"))
        }
        Scalar::I32 => {
            if scale == 1.0 {
                return Ok(format!("({text})"));
            }
            let value = text.parse::<i32>().map_err(|error| error.to_string())? as f64 * scale;
            if value.fract() != 0.0 || value < i32::MIN as f64 || value > i32::MAX as f64 {
                return Err("unit scaling does not produce a representable i32 literal".into());
            }
            Ok(format!("({})", value as i32))
        }
        Scalar::I64 => {
            if scale == 1.0 {
                return Ok(format!("({text})"));
            }
            let value = text.parse::<i64>().map_err(|error| error.to_string())? as f64 * scale;
            if value.fract() != 0.0 || value < i64::MIN as f64 || value > i64::MAX as f64 {
                return Err("unit scaling does not produce a representable i64 literal".into());
            }
            Ok(format!("({})", value as i64))
        }
        Scalar::Bool | Scalar::Complex64 | Scalar::Complex128 => Err(
            "use a typed complex literal for complex64; boolean numeric literals are invalid"
                .into(),
        ),
    }
}

pub fn semantic_json(checked: &CheckedProgram) -> String {
    let mut out = String::from("{\n  \"schema\": \"vibe.semantic.v0\",\n  \"functions\": [\n");
    for (i, f) in checked.program.functions.iter().enumerate() {
        if i > 0 {
            out.push_str(",\n");
        }
        let calls = checked
            .calls
            .get(&f.id)
            .cloned()
            .unwrap_or_default()
            .into_iter()
            .map(|x| format!("\"{}\"", json_escape(&x)))
            .collect::<Vec<_>>()
            .join(", ");
        let effects = checked
            .effects
            .get(&f.id)
            .into_iter()
            .flatten()
            .map(|effect| format!("\"{}\"", json_escape(effect)))
            .collect::<Vec<_>>()
            .join(", ");
        out.push_str(&format!("    {{\"id\": \"{}\", \"kind\": \"function\", \"line\": {}, \"calls\": [{}], \"effects\": [{}]}}", json_escape(&f.id), f.line, calls, effects));
    }
    out.push_str("\n  ]\n}\n");
    out
}

fn json_escape(s: &str) -> String {
    s.replace('\\', "\\\\").replace('"', "\\\"")
}

fn c_string(s: &str) -> String {
    let mut out = String::new();
    for c in s.chars() {
        match c {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c if c.is_ascii_graphic() || c == ' ' => out.push(c),
            c => {
                let mut buffer = [0; 4];
                for byte in c.encode_utf8(&mut buffer).as_bytes() {
                    out.push_str(&format!("\\{byte:03o}"));
                }
            }
        }
    }
    out
}

pub fn architecture(checked: &CheckedProgram) -> String {
    let callers = caller_index(checked);
    let mut out = String::from("Vibe program architecture\n\n");
    for f in &checked.program.functions {
        let calls = checked.calls.get(&f.id).cloned().unwrap_or_default();
        out.push_str(&format!(
            "{}\n  calls: {}\n  called by: {}\n  units: checked\n  effects: {}\n",
            f.id,
            if calls.is_empty() {
                "-".into()
            } else {
                calls.join(", ")
            },
            callers
                .get(f.id.as_str())
                .map(|x| x.join(", "))
                .unwrap_or_else(|| "-".into()),
            display_effects(checked, &f.id)
        ));
    }
    out
}

pub fn object_view(checked: &CheckedProgram, id: &str) -> Result<String, String> {
    let function = checked
        .program
        .functions
        .iter()
        .find(|function| function.id == id)
        .ok_or_else(|| format!("unknown semantic object '{id}'"))?;
    let callers = caller_index(checked);
    let callees = checked.calls.get(id).cloned().unwrap_or_default();
    let parameters = function
        .params
        .iter()
        .map(|param| format!("{}: {}", param.name, display_type(&param.ty)))
        .collect::<Vec<_>>()
        .join(", ");
    Ok(format!(
        "Semantic object\n\n{id}\n  kind: function\n  interface: ({parameters}) -> {}\n  calls: {}\n  called by: {}\n  effects: {}\n  status: types and units checked\n",
        display_type(&function.result),
        display_ids(&callees),
        callers
            .get(id)
            .map(|ids| display_refs(ids))
            .unwrap_or_else(|| "-".into()),
        display_effects(checked, id),
    ))
}

pub fn object_json(checked: &CheckedProgram, id: &str) -> Result<String, String> {
    let function = checked
        .program
        .functions
        .iter()
        .find(|function| function.id == id)
        .ok_or_else(|| format!("unknown semantic object '{id}'"))?;
    let callers = caller_index(checked)
        .get(id)
        .map(|ids| ids.iter().map(|id| (*id).to_string()).collect::<Vec<_>>())
        .unwrap_or_default();
    let callees = checked.calls.get(id).cloned().unwrap_or_default();
    let parameters = function
        .params
        .iter()
        .map(|parameter| {
            format!(
                "{{\"name\":\"{}\",\"type\":\"{}\"}}",
                json_escape(&parameter.name),
                json_escape(&display_type(&parameter.ty))
            )
        })
        .collect::<Vec<_>>()
        .join(",");
    let calls = json_strings(&callees);
    let called_by = json_strings(&callers);
    let effects = checked
        .effects
        .get(id)
        .map(|effects| json_strings(&effects.iter().cloned().collect::<Vec<_>>()))
        .unwrap_or_default();
    Ok(format!(
        "{{\"schema\":\"vibe.object.v0\",\"object\":{{\"id\":\"{}\",\"kind\":\"function\",\"parameters\":[{}],\"result\":\"{}\",\"calls\":[{}],\"called_by\":[{}],\"effects\":[{}],\"status\":\"checked\"}}}}\n",
        json_escape(id),
        parameters,
        json_escape(&display_type(&function.result)),
        calls,
        called_by,
        effects
    ))
}

pub fn callees(checked: &CheckedProgram, id: &str) -> Result<Vec<String>, String> {
    require_object(checked, id)?;
    Ok(checked.calls.get(id).cloned().unwrap_or_default())
}

pub fn callers(checked: &CheckedProgram, id: &str) -> Result<Vec<String>, String> {
    require_object(checked, id)?;
    Ok(caller_index(checked)
        .get(id)
        .map(|ids| ids.iter().map(|id| (*id).to_string()).collect())
        .unwrap_or_default())
}

pub fn impact(checked: &CheckedProgram, id: &str) -> Result<Vec<String>, String> {
    require_object(checked, id)?;
    let callers = caller_index(checked);
    let mut pending = vec![id.to_string()];
    let mut affected = Vec::new();
    while let Some(current) = pending.pop() {
        if let Some(next) = callers.get(current.as_str()) {
            for caller in next {
                if *caller != id && !affected.contains(&caller.to_string()) {
                    affected.push(caller.to_string());
                    pending.push(caller.to_string());
                }
            }
        }
    }
    affected.sort();
    Ok(affected)
}

fn require_object(checked: &CheckedProgram, id: &str) -> Result<(), String> {
    if checked.functions.contains_key(id) {
        Ok(())
    } else {
        Err(format!("unknown semantic object '{id}'"))
    }
}

fn caller_index(checked: &CheckedProgram) -> BTreeMap<&str, Vec<&str>> {
    let mut callers: BTreeMap<&str, Vec<&str>> = BTreeMap::new();
    for (caller, callees) in &checked.calls {
        for callee in callees {
            callers.entry(callee).or_default().push(caller);
        }
    }
    callers
}

fn display_type(ty: &TypeSyntax) -> String {
    match ty {
        TypeSyntax::Scalar(scalar, unit) => match unit {
            Some(unit) => format!("{}[{unit}]", scalar.name()),
            None => scalar.name().into(),
        },
        TypeSyntax::Array {
            element,
            rank,
            unit,
            mutable,
        } => format!(
            "{}Array<{},{}>{}",
            if *mutable { "mut " } else { "" },
            element.name(),
            rank,
            unit.as_ref()
                .map(|unit| format!("[{unit}]"))
                .unwrap_or_default()
        ),
        TypeSyntax::None => "none".into(),
    }
}

fn display_ids(ids: &[String]) -> String {
    if ids.is_empty() {
        "-".into()
    } else {
        ids.join(", ")
    }
}

fn display_refs(ids: &[&str]) -> String {
    if ids.is_empty() {
        "-".into()
    } else {
        ids.join(", ")
    }
}

fn display_effects(checked: &CheckedProgram, id: &str) -> String {
    checked
        .effects
        .get(id)
        .filter(|effects| !effects.is_empty())
        .map(|effects| effects.iter().cloned().collect::<Vec<_>>().join(", "))
        .unwrap_or_else(|| "none".into())
}

fn json_strings(values: &[String]) -> String {
    values
        .iter()
        .map(|value| format!("\"{}\"", json_escape(value)))
        .collect::<Vec<_>>()
        .join(",")
}

#[cfg(test)]
mod tests {
    use super::mangle;

    #[test]
    fn semantic_identity_mangling_is_collision_free_for_punctuation() {
        assert_ne!(mangle("@a.b"), mangle("@a_b"));
    }

    #[test]
    fn local_names_cannot_collide_with_array_storage() {
        assert_ne!(
            format!("{}_storage", super::local_name("x")),
            super::local_name("x_storage")
        );
    }
}
