use crate::ast::*;
use crate::check::CheckedProgram;
use crate::units;
use std::collections::{BTreeMap, HashMap};

pub fn emit_c(checked: &CheckedProgram) -> Result<String, String> {
    let mut out = String::from(
        "/* generated by vibec; do not edit */\n#include <stdint.h>\n#include <stdbool.h>\n#include <stddef.h>\n#include <stdio.h>\n\ntypedef struct { float *data; size_t len; } vibe_array_f32;\ntypedef struct { double *data; size_t len; } vibe_array_f64;\ntypedef struct { int32_t *data; size_t len; } vibe_array_i32;\ntypedef struct { int64_t *data; size_t len; } vibe_array_i64;\n\n",
    );
    for f in &checked.program.functions {
        out.push_str(&signature(f));
        out.push_str(";\n");
    }
    out.push('\n');
    for f in &checked.program.functions {
        out.push_str(&signature(f));
        out.push_str(" {\n");
        let mut env: HashMap<String, TypeSyntax> = f
            .params
            .iter()
            .map(|p| (p.name.clone(), p.ty.clone()))
            .collect();
        emit_block(&f.body, &mut env, 1, &mut out)?;
        out.push_str("}\n\n");
    }
    if checked
        .program
        .functions
        .iter()
        .any(|f| f.id == "@app.main")
    {
        out.push_str("int main(void) { return (int)vibe_app_main(); }\n");
    }
    Ok(out)
}

fn signature(f: &Function) -> String {
    let params = if f.params.is_empty() {
        "void".into()
    } else {
        f.params
            .iter()
            .map(|p| format!("{} {}", c_type(&p.ty), p.name))
            .collect::<Vec<_>>()
            .join(", ")
    };
    format!("{} {}({})", c_type(&f.result), mangle(&f.id), params)
}

fn emit_block(
    body: &[Stmt],
    env: &mut HashMap<String, TypeSyntax>,
    depth: usize,
    out: &mut String,
) -> Result<(), String> {
    let pad = "    ".repeat(depth);
    for stmt in body {
        match stmt {
            Stmt::Let {
                name,
                mutable: _,
                annotation,
                value: Expr::Array(values),
            } => {
                if values.is_empty() {
                    return Err("empty array code generation is unsupported".into());
                }
                let element = match annotation {
                    Some(TypeSyntax::Array { element, .. }) => element.clone(),
                    _ => match &values[0] {
                        Expr::Number { scalar, .. } => scalar.clone(),
                        _ => return Err("array literal element type must be explicit".into()),
                    },
                };
                out.push_str(&format!(
                    "{pad}{} {name}_storage[] = {{",
                    scalar_c(&element)
                ));
                for (i, v) in values.iter().enumerate() {
                    if i > 0 {
                        out.push_str(", ");
                    }
                    out.push_str(&emit_expr(v)?);
                }
                out.push_str("};\n");
                out.push_str(&format!(
                    "{pad}vibe_array_{} {name} = {{ {name}_storage, {} }};\n",
                    element.name(),
                    values.len()
                ));
                let unit = match annotation {
                    Some(TypeSyntax::Array { unit, .. }) => unit.clone(),
                    _ => match &values[0] {
                        Expr::Number { unit, .. } => unit.clone(),
                        _ => None,
                    },
                };
                env.insert(
                    name.clone(),
                    TypeSyntax::Array {
                        element,
                        rank: 1,
                        unit,
                        mutable: true,
                    },
                );
            }
            Stmt::Let {
                name,
                annotation,
                value,
                ..
            } => {
                let ty = annotation
                    .clone()
                    .unwrap_or_else(|| infer_syntax(value, env));
                out.push_str(&format!(
                    "{pad}{} {name} = {};\n",
                    c_type(&ty),
                    emit_expr(value)?
                ));
                env.insert(name.clone(), ty);
            }
            Stmt::Assign { target, value } => out.push_str(&format!(
                "{pad}{} = {};\n",
                emit_expr(target)?,
                emit_expr(value)?
            )),
            Stmt::For {
                index,
                start,
                end,
                body,
            } => {
                out.push_str(&format!(
                    "{pad}for (int64_t {index} = {}; {index} < {}; ++{index}) {{\n",
                    emit_expr(start)?,
                    emit_expr(end)?
                ));
                env.insert(index.clone(), TypeSyntax::Scalar(Scalar::I64, None));
                emit_block(body, env, depth + 1, out)?;
                env.remove(index);
                out.push_str(&format!("{pad}}}\n"));
            }
            Stmt::Return(Some(v)) => out.push_str(&format!("{pad}return {};\n", emit_expr(v)?)),
            Stmt::Return(None) => out.push_str(&format!("{pad}return;\n")),
            Stmt::Print {
                value: Expr::String(value),
                ..
            } => {
                out.push_str(&format!("{pad}puts(\"{}\");\n", c_string(value)));
            }
            Stmt::Print { value, unit } => {
                let divisor = unit
                    .as_deref()
                    .map(|u| units::parse(Some(u)).map(|x| x.scale))
                    .transpose()?
                    .unwrap_or(1.0);
                let suffix = unit.as_deref().unwrap_or("1");
                out.push_str(&format!(
                    "{pad}printf(\"%.12g {suffix}\\n\", (double)({}) / {:.17e});\n",
                    emit_expr(value)?,
                    divisor
                ));
            }
            Stmt::Expr(v) => out.push_str(&format!("{pad}(void)({});\n", emit_expr(v)?)),
        }
    }
    Ok(())
}

fn emit_expr(expr: &Expr) -> Result<String, String> {
    Ok(match expr {
        Expr::String(_) => return Err("string values are only valid directly inside print".into()),
        Expr::Number { text, scalar, unit } => {
            let scale = units::parse(unit.as_deref())?.scale;
            let suffix = if *scalar == Scalar::F32 { "f" } else { "" };
            if scale == 1.0 {
                format!("({}{suffix})", text)
            } else {
                format!("(({}{suffix}) * {:.17e})", text, scale)
            }
        }
        Expr::Var(name) => name.clone(),
        Expr::Array(_) => return Err("array literal is only valid in a let binding".into()),
        Expr::Index { array, index } => {
            format!("({}).data[{}]", emit_expr(array)?, emit_expr(index)?)
        }
        Expr::Call { function, args } if function == "len" => {
            format!("(int64_t)({}).len", emit_expr(&args[0])?)
        }
        Expr::Call { function, args } => format!(
            "{}({})",
            mangle(function),
            args.iter()
                .map(emit_expr)
                .collect::<Result<Vec<_>, _>>()?
                .join(", ")
        ),
        Expr::Binary { op, left, right } => {
            format!("({} {op} {})", emit_expr(left)?, emit_expr(right)?)
        }
        Expr::Unary { op, value } => format!("({op}{})", emit_expr(value)?),
    })
}

fn infer_syntax(expr: &Expr, env: &HashMap<String, TypeSyntax>) -> TypeSyntax {
    match expr {
        Expr::String(_) => TypeSyntax::None,
        Expr::Number { scalar, unit, .. } => TypeSyntax::Scalar(scalar.clone(), unit.clone()),
        Expr::Var(v) => env.get(v).cloned().unwrap_or(TypeSyntax::None),
        Expr::Array(v) => match v.first() {
            Some(Expr::Number { scalar, unit, .. }) => TypeSyntax::Array {
                element: scalar.clone(),
                rank: 1,
                unit: unit.clone(),
                mutable: true,
            },
            _ => TypeSyntax::None,
        },
        Expr::Index { array, .. } => match infer_syntax(array, env) {
            TypeSyntax::Array { element, unit, .. } => TypeSyntax::Scalar(element, unit),
            _ => TypeSyntax::None,
        },
        Expr::Binary { left, .. } | Expr::Unary { value: left, .. } => infer_syntax(left, env),
        Expr::Call { .. } => TypeSyntax::Scalar(Scalar::F64, None),
    }
}

fn c_type(ty: &TypeSyntax) -> String {
    match ty {
        TypeSyntax::Scalar(s, _) => scalar_c(s).into(),
        TypeSyntax::Array { element, .. } => format!("vibe_array_{}", element.name()),
        TypeSyntax::None => "void".into(),
    }
}
fn scalar_c(s: &Scalar) -> &'static str {
    match s {
        Scalar::Bool => "bool",
        Scalar::I32 => "int32_t",
        Scalar::I64 => "int64_t",
        Scalar::F32 => "float",
        Scalar::F64 => "double",
    }
}
pub fn mangle(id: &str) -> String {
    format!("vibe_{}", id.trim_start_matches('@').replace('.', "_"))
}

pub fn semantic_json(checked: &CheckedProgram) -> String {
    let mut out = String::from("{\n  \"schema\": \"vibe.semantic.v0\",\n  \"functions\": [\n");
    for (i, f) in checked.program.functions.iter().enumerate() {
        if i > 0 {
            out.push_str(",\n");
        }
        let calls = checked
            .calls
            .get(&f.id)
            .cloned()
            .unwrap_or_default()
            .into_iter()
            .map(|x| format!("\"{}\"", json_escape(&x)))
            .collect::<Vec<_>>()
            .join(", ");
        out.push_str(&format!("    {{\"id\": \"{}\", \"kind\": \"function\", \"line\": {}, \"calls\": [{}], \"effects\": []}}", json_escape(&f.id), f.line, calls));
    }
    out.push_str("\n  ]\n}\n");
    out
}

fn json_escape(s: &str) -> String {
    s.replace('\\', "\\\\").replace('"', "\\\"")
}

fn c_string(s: &str) -> String {
    let mut out = String::new();
    for c in s.chars() {
        match c {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c if c.is_ascii_graphic() || c == ' ' => out.push(c),
            c => out.push_str(&format!("\\u{:04x}", c as u32)),
        }
    }
    out
}

pub fn architecture(checked: &CheckedProgram) -> String {
    let mut callers: BTreeMap<&str, Vec<&str>> = BTreeMap::new();
    for (caller, callees) in &checked.calls {
        for callee in callees {
            callers.entry(callee).or_default().push(caller);
        }
    }
    let mut out = String::from("Vibe program architecture\n\n");
    for f in &checked.program.functions {
        let calls = checked.calls.get(&f.id).cloned().unwrap_or_default();
        out.push_str(&format!(
            "{}\n  calls: {}\n  called by: {}\n  units/effects: checked / none\n",
            f.id,
            if calls.is_empty() {
                "-".into()
            } else {
                calls.join(", ")
            },
            callers
                .get(f.id.as_str())
                .map(|x| x.join(", "))
                .unwrap_or_else(|| "-".into())
        ));
    }
    out
}
